#!/bin/bash
echo "Video Streaming for the Beaglebone - derekmolloy.ie"
echo "Piping the output of capture to avconv"

# Next line not necessary if you are using my -F option on capture
v4l2-ctl --device=/dev/video0 --set-parm=30 --set-fmt-video=width=160,height=60,pixelformat=1

# Pipe the output of capture into avconv/ffmpeg 
# capture "-F"   My H264 passthrough mode
#	  "-o"   Output the video (to be passed to avconv via pipe)
#	  "-c0"  Capture 0 frames, which means infinite frames in my program
# avconv "-re" read input at the native frame rate
#        "-i -"  Take the input from the pipe
#	 "-vcodec copy" Do not transcode the video
# 	 "-f rtp rtp://192.168.1.2:1234/" Force rtp to output to address of my PC on port 1234
STREAM_URL="rtmp://live.justin.tv/app/live_54496724_3qqDdB7J04WgaJmhO8qvbkpbYwOmYZ"

complete=1
while [ $complete == 1 ] 
do
./capture -F -o -c0|ffmpeg -f h264 -y -analyzeduration 10M -probesize 10M -framerate 20 -rtbufsize 1000k -i - -vcodec libx264 -b:v 625k -minrate:v 625k -bt:v 100k -maxrate:v 625k -bufsize 4000k -g:v 2 -vprofile baseline -level 21 -threads:v 0 -preset ultrafast -r:v 30 -strict experimental -qmin:v 2 -qmax:v 52 -q:v 20 -sn -acodec libmp3lame -b:a 44100 -f flv "$STREAM_URL"
return=$?
  if [ $return == 0 ]; then
     complete=1
  fi
  if [ $return == 1 ]; then
     sleep 1
  fi
done
